FROM mcr.microsoft.com/devcontainers/cpp:ubuntu

# Set the working directory in the container
WORKDIR /usr/src/app

# Install necessary build tools and libraries
RUN apt-get update && \
    apt-get install -y g++ && \
    rm -rf /var/lib/apt/lists/*

# Copy the C++ source code files into the container
ADD ./ ./

# Compile the program
RUN make clean
RUN make
 
# Set the default command to run the compiled program
CMD ["./bin/advent_of_code"]
